name: CI / CD
on: [push, pull_request]

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:      
  #     - uses: actions/checkout@v2
  #     - run: |
  #         sudo apt-get install -y libgeos-c1v5
  #     - uses: actions/setup-python@v1
  #       with: 
  #         python-version: '3.9.x'
  #     - run: |
  #         pip install -U pip poetry
  #         poetry install -E shapely
  #       env:
  #         POETRY_VIRTUALENVS_CREATE: false
      
  #     - name: Run Tests
  #       run: poetry run py.test

  build:
    strategy:
      matrix:
        os: [windows]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with: 
          python-version: '3.9.x'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Poetry install
        run: poetry install --no-interaction --no-root
      - name: Run the build process
        run: poetry run pyinstaller --onefile preprocess_cancellation.py
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: preprocess_cancellation-${{ matrix.os }}
          path: |
            dist

  # release:
  #   runs-on: ubuntu-latest
  #   needs: [test, build]
  #   if: startsWith(github.ref, 'refs/tags/')
  #   steps:
  #     - uses: actions/download-artifact@v2
      
  #     - name: Release tags
  #       uses: softprops/action-gh-release@v1
  #       with:
  #        files: |
  #          */preprocess_cancellation-*.zip